// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelNodeCheck() {
  return window['go']['main']['App']['CancelNodeCheck']();
}

export function CancelTest() {
  return window['go']['main']['App']['CancelTest']();
}

export function CheckNodes() {
  return window['go']['main']['App']['CheckNodes']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListNodes() {
  return window['go']['main']['App']['ListNodes']();
}

export function StartTest(arg1) {
  return window['go']['main']['App']['StartTest'](arg1);
}
