// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelNodeCheck():Promise<void>;

export function CancelTest():Promise<void>;

export function CheckNodes():Promise<main.NodeCheckResult>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetStatus():Promise<main.StatusResult>;

export function ListNodes():Promise<main.NodeListResult>;

export function StartTest(arg1:main.StartOptions):Promise<main.StartTestResult>;
